name : Build and Release I-Wallet

on:
    push:
      tags:
        - 'v*'
      branches:
        - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64]

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # Шаг 3: Установка fyne-cross
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      # Шаг 4: Сборка приложения
      - name: Build i-wallet for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          fyne-cross ${{ matrix.os }} -arch ${{ matrix.arch }} -output i-wallet -app-id com.example.iwallet
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      # Шаг 5: Загрузка артефактов
      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}/i-wallet
          asset_name: i-wallet-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
  release:
    name: Create Release and Upload Assets
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Создание релиза
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This is the automated release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 3: Загрузка артефактов в релиз
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fyne-cross/dist
          asset_name: i-wallet-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream