name: Build and Release i-wallet

on:
  push:
    tags:
      - 'v*' 
    branches:
      - main 

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.2

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      
      - name: Install mingw-w64
        run: sudo apt-get install -y mingw-w64

      - name: Build i-wallet for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          fyne-cross ${{ matrix.os }} -arch ${{ matrix.arch }} -output i-wallet -app-id com.example.iwallet -icon ./assets/Icon.png
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
    
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: i-wallet-${{ matrix.os }}-${{ matrix.arch }}
          path: ./fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}/i-wallet

      - name: Update GitHub Release if it exists
        run: |
            TAG_NAME=${{ github.ref_name }}
            RELEASE_ID=$(gh release view $TAG_NAME --json id -q ".id")
            if [ "$RELEASE_ID" ]; then
            echo "Release already exists. Updating release..."
            gh release edit $TAG_NAME --draft false --prerelease false --notes "Updated release for version $TAG_NAME"
            else
            echo "Creating new release..."
            gh release create $TAG_NAME --title "Release $TAG_NAME" --notes "Automated release for version $TAG_NAME"
            fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}/i-wallet
          asset_name: i-wallet-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream