name: Build and Release i-wallet

on:
  push:
    tags:
      - 'v*' 
    branches:
      - main 

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Build i-wallet for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          fyne-cross ${{ matrix.os }} -arch ${{ matrix.arch }} -output i-wallet -app-id com.example.iwallet
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: List files after build
        run: ls -alh ./fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: i-wallet-${{ matrix.os }}-${{ matrix.arch }}
          path: ./fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}/i-wallet

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fyne-cross/dist/${{ matrix.os }}-${{ matrix.arch }}/i-wallet
          asset_name: i-wallet-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream