name : Build and Release Fyne App

on:
    release:
      types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest

      - name: Build for Windows
        run: fyne-cross windows -arch amd64 -output i-wallet

      - name: Build for macOS
        run: fyne-cross darwin -arch amd64 -output i-wallet

      - name: Build for Linux
        run: fyne-cross linux -arch amd64 -output i-wallet

      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./fyne-cross/dist/windows-amd64/i-wallet.exe
            asset_content_type: application/octet-stream
            asset_name: i-wallet-windows-amd64.exe